skuid/skuid-cli

README.md
cmd/page-pack.go
cmd/pull.go
cmd/push.go
cmd/retrieve.go
cmd/root.go
force/force.go
platform/platform.go
pliny/pliny.go
types/platform.go
types/skuid.go

- Adds login / connection utilities for Skuid Platform
- Adds new command `skuid retrieve` which currently only supports retrieving all metadata because that's all the API supports (for now, but Ben is working on that...)
- Adjusts documentation and command API's to support both Platforms

Adds support for retrieving metadata from Skuid Platform

---

README.md
cmd/deploy.go
cmd/retrieve.go
platform/platform.go

Addresses #8 - Add deploy command

#3: Add deploy command

---

README.md
cmd/root.go

This PR expands the existing README to include additional information on usage, the structure of retrieved files, and troubleshooting steps. I've also suggested two help text updates for a typo and proper host URL structure.

README + help text updates

---

cmd/pull.go
cmd/root.go

Our Page API currently only support pulling pages by Module name. Heidrick and Struggles (as well as internal users here at Skuid) are requesting the ability to pulling one or more pages by name, rather than having to pull an entire module at a time (hitting heap errors).

CORE-1469: Support Pulling Pages by Name

---

cmd/deploy.go
cmd/retrieve.go
platform/platform.go
types/plan.go
ziputils/ziputils.go

Do not merge yet. Just getting this code in for a handoff.

Plin 1584 support v2

---

cmd/retrieve.go
platform/platform.go

1. Used the result of a function before checking for error state.
2. Handle non 200 http codes from logins

Improves error handling for login failures

---

Makefile
README.md
version/version.go

Bumps version to 0.3.4 so we can make a release for theme deploy/retrieve.

Version Bump

---

Makefile
README.md
types/plan.go
version/version.go

Not sure how this worked locally before I changed the metadata struct, but I guess I derped on a git stash or something.

Also deploy design systems

---

Makefile
README.md
cmd/deploy.go
cmd/retrieve.go
httperror/httperror.go
platform/platform.go
text/text.go
version/version.go

1. Added a text package to make our console messaging more consistent and easier to read.
2. Improved the handling of JSON encoded http errors. Now they are returned to the user not as JSON.
3. Added some basic timing outputs for the duration http calls.
4. Added and made more consistent verbose outputs.

More improvements to error handling.

---

Makefile
README.md
version/version.go

Bump all the versions for a new release.

Make release 0.3.10

---

README.md

Rename to bolded on README & https://docs.skuid.com/latest/en/skuid/cli/
README: wget https://<span></span>github.com/skuid/**skuid-cli**/releases/download/3/skuid_darwin_amd64 -O skuid
Docs: wget $(curl https://<span></span>api.github.com/repos/skuid/**skuid-cli**/releases/latest | grep browser_download_url | grep darwin | awk -F '"' '{print $4}') -O skuid

README: Rename "skuid" -> "skuid-cli"

---

types/plan.go

https://skuidify.atlassian.net/browse/PLIN-2456
https://github.com/skuid/pliny/pull/912
https://github.com/skuid/warden/pull/364
https://github.com/skuid/skuid-cli/pull/67

PLIN-2456 Add permissionsets to the plan type

---

cmd/variables.go
go.mod
go.sum

https://skuidify.atlassian.net/browse/PLIN-2645

Remove "Delete Variable"  from CLI capabilities

---

cmd/deploy.go

This was silently erroring out when testing locally.

PLIN-3019: Actually implement target directory swap

---

cmd/deploy.go

https://skuidify.atlassian.net/browse/PLIN-3107

Fix directory changing bug

---

pkg/metadata.go
pkg/metadata_test.go

[PLIN-3427](https://skuidify.atlassian.net/browse/PLIN-3427)
===
Just some renaming of metadata variables. It should be reviewed in conjunction with [Pliny's PR](https://github.com/skuid/pliny/pull/1670).

PLIN-3427 metadata renaming

---

README.md

https://skuidify.atlassian.net/browse/DOCS-2387
Update repository README to reflect current status and add links for more information
-

Update README with project's current status and appropriate links

---

.drone.yml

https://inflight.atlassian.net/browse/PLIN-4093
Fix drone manifest
-  Fix drone manifest

Fixed drone manifest

---

cmd/deploy.go

https://inflight.atlassian.net/browse/PLIN-4173
- Setting default directory for deployment process
- Setting default directory for deployment process

PLIN-4173-skuid-cli-0-6-0-alpha-deploy-from-current-directory-if-none-specified

---

pkg/metadata.go

https://inflight.atlassian.net/browse/PLIN-4201
Added sessionvariables metadatada
- Added sessionvariables metadatada

PLIN-4201-support-session-variable-retrieve-deploy-with-cli

---

cmd/root.go

https://inflight.atlassian.net/browse/PLIN-4244
Set custom version message according to the rest of commands
- Set custom version message according to the rest of commands

PLIN-4244-change-skuid-cli-version-to-skuid-cli-version

---

pkg/deploy.go
pkg/plan.go

https://inflight.atlassian.net/browse/PLIN-4404
Fix app permission set DSO permissions CLI deploy
- Modify the NewPermissionSets logic so that it includes all permission set information, including its datasource permission information
Review in conjunction with:
https://github.com/skuid/pliny/pull/2011
https://github.com/skuid/warden/pull/587

PLIN-4404: Fix app permission set deploy

---

README.md

- Removed 0.5.0 from the readme

Update README.md to remove 0.5.0 reference
